- name: 西南四省（云贵川渝）
  env:
    FEISHU_APP_ID: ${{ secrets.FEISHU_APP_ID }}
    FEISHU_APP_SECRET: ${{ secrets.FEISHU_APP_SECRET }}
    RECEIVE_OPEN_ID_POLICY: ${{ secrets.RECEIVE_OPEN_ID_SW }}
    DEEPSEEK_API_KEY: ${{ secrets.DEEPSEEK_API_KEY }}
  run: python scripts/policy_tracker.py

- name: 北京天津东北内蒙古
  env:
    FEISHU_APP_ID: ${{ secrets.FEISHU_APP_ID }}
    FEISHU_APP_SECRET: ${{ secrets.FEISHU_APP_SECRET }}
    RECEIVE_OPEN_ID_POLICY: ${{ secrets.RECEIVE_OPEN_ID_BJ_TJ_DB }}
    DEEPSEEK_API_KEY: ${{ secrets.DEEPSEEK_API_KEY }}
  run: python scripts/policy_tracker_doc.py

- name: 陕西甘肃西藏宁夏
  env:
    FEISHU_APP_ID: ${{ secrets.FEISHU_APP_ID }}
    FEISHU_APP_SECRET: ${{ secrets.FEISHU_APP_SECRET }}
    RECEIVE_OPEN_ID_POLICY: ${{ secrets.RECEIVE_OPEN_ID_SXGSXZNX }}
    DEEPSEEK_API_KEY: ${{ secrets.DEEPSEEK_API_KEY }}
  run: python scripts/policy_tracker_sxgsxznx.py

- name: 山东省
  env:
    FEISHU_APP_ID: ${{ secrets.FEISHU_APP_ID }}
    FEISHU_APP_SECRET: ${{ secrets.FEISHU_APP_SECRET }}
    RECEIVE_OPEN_ID_POLICY: ${{ secrets.RECEIVE_OPEN_ID_SHANDONG }}
    DEEPSEEK_API_KEY: ${{ secrets.DEEPSEEK_API_KEY }}
  run: python scripts/policy_tracker_shandong.py
